services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project_manager

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_manager
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql_script.txt:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./sql_data.txt:/docker-entrypoint-initdb.d/02_data.sql:ro

volumes:
  db_data: