services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_manager
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./web-2025/sql_script.txt:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./web-2025/sql_data.txt:/docker-entrypoint-initdb.d/02_data.sql:ro

  php:
    build: ./web-2025
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project_manager
    ports:
      - "8000:8000"
    volumes:
      - ./web-2025:/var/www/html
      - ./web-2025/public/uploads:/var/www/html/public/uploads

volumes:
  db_data: