name: Project Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main-checks:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: project_manager
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, mysqli
          coverage: xdebug

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h"127.0.0.1" -uroot -proot --silent; then
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Import database schema
        run: |
          mysql -h127.0.0.1 -uroot -proot project_manager < sql_script.txt

      - name: PHP Lint
        run: find . -type f -name "*.php" -exec php -l {} \;

      - name: PHPStan (Static Analysis)
        run: vendor/bin/phpstan analyse || true

      - name: Run PHPUnit tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: project_manager
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --testdox
          else
            echo "No PHPUnit tests found. TBA."
          fi
